# vim: set ft=yaml ts=2 expandtab:
---

# use absolute path to virtualenv
# https://github.com/ansible/ansible/issues/22967
#
molecule_virtualenv: "{{ ansible_user_dir }}/.virtualenvs/molecule"

molecule_major_version: 2
molecule_ansible_version: 2.9
...
