# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: t_centos6
    image: centos:6
  - name: t_centos7
    image: centos:7
  - name: t_centos8
    image: centos:8
  - name: t_fedora30
    image: fedora:30
  - name: t_fedora31
    image: fedora:31
  - name: t_fedorarawhide
    image: fedora:rawhide
  - name: t_ubuntu16
    image: ubuntu:xenial
  - name: t_ubuntu18
    image: ubuntu:bionic
  - name: t_ubuntu20
    image: ubuntu:focal
provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
  config_options:
    defaults:
      interpreter_python: auto
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
