# vim: set ft=yaml ts=2 expandtab:
---

- name: get OS specific variables
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"

- name: molecule_ansible_version
  debug:
    var: molecule_ansible_version
  tags:
  - never
  - debug

- name: epel is present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  become: true
  package:
    name: epel-release

- name: molecules dependencies are present
  become: true
  package:
    name: "{{ molecule_system_dependencies }}"

# use absolute path to virtualenv
# https://github.com/ansible/ansible/issues/22967
#
# and do not use site packages
# https://github.com/ansible/molecule/issues/1888
#
- name: specific ansible version is installed
  when:
  - molecule_ansible_version is defined
  pip:
    name:
    - ansible=={{ molecule_ansible_version }}.*
    virtualenv: "{{ molecule_virtualenv }}"

# use absolute path to virtualenv
# https://github.com/ansible/ansible/issues/22967
#
# and do not use site packages
# https://github.com/ansible/molecule/issues/1888
#
- name: molecule is installed
  pip:
    name:
    - ansible
    - molecule=={{ molecule_major_version }}.*
    virtualenv: "{{ molecule_virtualenv }}"

# use absolute path to virtualenv
# https://github.com/ansible/ansible/issues/22967
#
# and do not use site packages
# https://github.com/ansible/molecule/issues/1888
#
# for some reason i had to split it out to a separate task
# molecule and molecule[docker] in the same pip task did not work
#
- name: molecule[docker] is installed
  pip:
    name:
    - molecule[docker]
    virtualenv: "{{ molecule_virtualenv }}"

# _ansible_version does not work, i use _ansibles_version
# reserved variable ?
#
- name: get ansible version
  changed_when: false
  command: "{{ molecule_virtualenv }}/bin/ansible --version"
  register: _ansibles_version

- name: ansible version
  debug:
    var: _ansibles_version.stdout
  tags:
  - never
  - debug

- name: assertions
  when:
  - molecule_ansible_version is defined
  assert:
    that:
    - _ansibles_version.stdout is match('ansible {{ molecule_ansible_version }}.*')

...
