---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: test_molecule_manual
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  #env:
  #  ANSIBLE_COLLECTION_PATHS: "/home/mafalb/Documents/ansible_collections"
verifier:
  name: ansible
  lint:
    name: ansible-lint
