# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntu1804
    image: ubuntu:bionic     
provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
verifier:
  name: ansible
  lint:
    name: ansible-lint
