# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: t_centos7
    image: centos:7
  - name: t_centos8
    image: centos:8
  - name: t_ubuntu1804
    image: ubuntu:bionic     
  - name: t_ubuntu1604
    image: ubuntu:xenial    
provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
verifier:
  name: ansible
  lint:
    name: ansible-lint
