# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  roles:

    - name: install node dependencies
      role: mafalb.ansible.node

    - name: install molecule with default settings
      role: mafalb.ansible.molecule

- name: Converge with a specific version of ansible
  hosts: all
  vars:
    ansibles_version: 2.8
  roles:
    - role: mafalb.ansible.node
    - role: mafalb.ansible.molecule
      molecule_ansible_version: "{{ ansibles_version }}"
      molecule_virtualenv: ~/.virtualenvs/molecule-{{ ansibles_version }}

...
