# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: all
  roles:

    - name: install molecule with default settings
      role: mafalb.ansible.molecule

    - name: install molecule with a specific version of ansible
      role: mafalb.ansible.molecule
      when: lookup('env','ANSIBLE_VERSION')
      molecule_ansible_version: "{{ lookup('env','ANSIBLE_VERSION') }}"
      molecule_virtualenv: ~/.virtualenvs/molecule-{{ lookup('env','ANSIBLE_VERSION') }}

...
