# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all
  tasks:

  - name: molecule is present in ~/.virtualenvs/molecule
    changed_when: false
    command: ~/.virtualenvs/molecule/bin/molecule --version
    register: _molecule_version

  - name: molecule is present ~/.virtualenvs/molecule-2.8
    changed_when: false
    command: ~/.virtualenvs/molecule-2.8/bin/molecule --version
    register: _molecule_version_28

  - name: molecule version
    loop:
    - _molecule_version.stdout
    - _molecule_version_28.stdout
    debug:
      var: "{{ item }}"

  - name: ansible is present
    changed_when: false
    environment:
      PATH: " ~/.virtualenvs/molecule:$PATH"
    command: ansible --version
    register: _ansibles_version

  - name: ansible 2.8 is present
    changed_when: false
    environment:
      PATH: " ~/.virtualenvs/molecule-2.8:$PATH"
    command: ansible --version
    register: _ansibles_version_28_env

  - name: ansible version
    loop:
    - _ansibles_version.stdout
    - _ansibles_version_28.stdout
    debug:
      var: "{{ item }}"

  - name: assertions
    assert:
      that:
      - _ansibles_version.stdout is match('ansible')
      - _ansibles_version_28.stdout is match('ansible 2.8.*')
      - _ansibles_version_28_env.stdout is match('ansible 2.8.*')

...
