# vim: set ft=yaml ts=2 expandtab:
---

- name: OS dependent variables
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"

- name: necessary packages are installed
  become: true
  package:
    name: "{{ ansible_node_dependencies }}"
    state: present

...
