# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -v

platforms:
  - name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
    image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
  config_options:
    defaults:
      interpreter_python: auto

verifier:
  name: ansible
  lint:
    name: ansible-lint
