# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint roles/*/vars/*.yml
  flake8 -v

# do not change the name of 
# the network molecule-internal
# it is hardcoded in create.yml
platforms:
- name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
  image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
  networks:
  - name: molecule-internal
  command: /lib/systemd/systemd
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true

- name: t_proxy
  image: centos:7
  command: /lib/systemd/systemd
  networks:
  - name: molecule-external
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true

provisioner:
  name: ansible
  playbooks:
    docker:
      create: create.yml
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
