# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  pull_request:  
  schedule:
  - cron: '30 18 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: install molecule
        run: ansible-playbook -D bootstrap.yml

      - name: run molecule
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule test

...
