# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  pull_request:  
  schedule:
  - cron: '40 12 * * 6'

jobs:

  node:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
      
        target:
        - centos7
        - centos8
        - ubuntu-18.04
        - ubuntu-16.04
        - fedora30
        - fedora31

        os:
        - ubuntu-18.04

        ansible_version:
        - 2.9
        - 2.8

        include:

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic

        - target: ubuntu-16.04
          distribution: ubuntu
          version: xenial

        - target: centos7
          distribution: centos
          version: 7

        - target: centos8
          distribution: centos
          version: 8

        - target: fedora30
          distribution: fedora
          version: 30

        - target: fedora31
          distribution: fedora
          version: 31

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}:${{ matrix.version }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
        
    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: cache pip cache
        uses: actions/cache@v1
        if: false
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: grep for forgotten no_log
        run: '! grep -r "no_log: false" roles'

      - name: install molecule
        run: ansible-playbook -D bootstrap.yml -t all,debug -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 CI_CONTAINER_IMAGE=${{ matrix.distribution }}:${{ matrix.version }} CI_CONTAINER_TAG=${{ matrix.version }} molecule test -s node

  molecule:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:

        target:
        - centos7
        - centos8
        - ubuntu-18.04
        - ubuntu-16.04
        - fedora30
        - fedora31

        os:
        - ubuntu-18.04

        ansible_version:
        - 2.9
        - 2.8

        include:

        - target: centos7
          distribution: centos
          version: 7

        - target: centos8
          distribution: centos
          version: 8

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic

        - target: ubuntu-16.04
          distribution: ubuntu
          version: xenial

        - target: fedora30
          distribution: fedora
          version: 30

        - target: fedora31
          distribution: fedora
          version: 31

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}:${{ matrix.version }}
      CI_CONTAINER_TAG: ${{ matrix.version }}

    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: cache pip cache
        uses: actions/cache@v1
        if: false
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install molecule
        run: ansible-playbook -D bootstrap.yml -t all,debug -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 CI_CONTAINER_IMAGE=${{ matrix.distribution }}:${{ matrix.version }} CI_CONTAINER_TAG=${{ matrix.version }} molecule test -s molecule

...
