# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  push:
  pull_request:  
  schedule:
  - cron: '40 12 * * 6'

jobs:

  node:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-18.04
        ansible_version:
        - 2.9
        - 2.8
        include:
        - distribution: centos
          version: 7
        - distribution: centos
          version: 8
        - distribution: ubuntu
          version: xenial
        - distribution: ubuntu
          version: bionic
        - distribution: fedora
          version: 30
        - distribution: fedora
          version: 31

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}:${{ matrix.version }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
        
    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: cache pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: grep for forgotten no_log
        run: '! grep -r "no_log: false" roles'

      - name: install molecule
        run: ansible-playbook -D bootstrap.yml -t all,debug -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: manual lint
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible-lint roles/*

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule test -s node

  molecule:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-16.04
        ansible_version:
        - 2.9
        - 2.8
        include:

        - os: ubuntu-18.04
          ansible_version: 2.9
          distribution: centos
          version: 8

        - os: ubuntu-16.04
          ansible_version: 2.9
          distribution: centos
          version: 8

        - os: ubuntu-18.04
          ansible_version: 2.8
          distribution: centos
          version: 8

        - os: ubuntu-16.04
          ansible_version: 2.8
          distribution: centos
          version: 8

        - os: ubuntu-18.04
          ansible_version: 2.9
          distribution: ubuntu
          version: xenial

        - os: ubuntu-18.04
          ansible_version: 2.9
          distribution: ubuntu
          version: xenial

        #- distribution: ubuntu
        #  version: bionic
        #- distribution: fedora
        #  version: 30
        #- distribution: fedora
        #  version: 31
               
    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}:${{ matrix.version }}
      CI_CONTAINER_TAG: ${{ matrix.version }}

    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
        with:
          path: ansible_collections/mafalb/ansible
      
      - name: cache pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/molecule/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install molecule
        run: ansible-playbook -D bootstrap.yml -t all,debug -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: build test images
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule create -s molecule

      - name: run molecule tests
        run: |
          source ~/.virtualenvs/molecule/bin/activate 
          PY_COLORS=1 molecule test -s molecule

...
