# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on: 
  - push
  - pull_request  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout collection ansible
        uses: actions/checkout@v1
      
      - name: install molecule
        run:
          ansible-playbook -D bootstrap.yml

      - name: run molecule
        run:
          source ~/.virtualenvs/molecule/bin/activate 
          molecule --version

      - name: execute molecule
        run: molecule --version

...
